#Just an attempt to build the robot project using gradle. This should fail if there are any obvious syntax errors pushed to master.

name: Gradle Build Test

#This will trigger when someone pushes to master
on:
  push:
    branches: [master]


jobs:
  #Make a new job called "build" that will do the build test
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

